<#
    Lab.psd1 -- the single source of truth for every layer-1 setting.

    A data file rather than variables spread through the scripts, so that
    docs/INTEGRATION-INVENTORY.md can name one place for each value and stay
    honest. Every entry here appears in that table with its reason.

    Paths are on D: deliberately. C: had 2.8 GB free when this lab was written;
    Hyper-V's own defaults point at C:\ProgramData and would fill it.
#>
@{
    # --- storage ----------------------------------------------------------
    LabRoot      = 'D:\filemover-lab'
    IsoDir       = 'D:\filemover-lab\iso'
    VhdDir       = 'D:\filemover-lab\vhd'
    VmDir        = 'D:\filemover-lab\vm'
    KeyDir       = 'D:\filemover-lab\keys'

    # The Rocky 9 minimal ISO, downloaded by hand into IsoDir. Named rather
    # than globbed: a glob that matches two ISOs picks one silently, and the
    # difference between 9.4 and 9.5 is exactly the kind of thing that makes a
    # test result unreproducible.
    InstallIso   = 'Rocky-9.5-x86_64-minimal.iso'

    # Built by New-KickstartIso.ps1. The volume label MUST be OEMDRV: that is
    # the label Anaconda scans for at boot and auto-loads ks.cfg from, which is
    # what makes the install unattended without editing kernel boot parameters
    # through a console we would otherwise have to drive.
    KickstartIso = 'filemover-ks.iso'

    # --- the VM -----------------------------------------------------------
    VmName       = 'fm-rocky9-01'
    Generation   = 2
    CpuCount     = 2
    MemoryMB     = 4096
    DiskGB       = 40

    # Static, not dynamic, memory. Dynamic memory makes a page-cache-sensitive
    # I/O test depend on what the host was doing at the time, and this lab
    # exists to make results reproducible.
    DynamicMemory = $false

    # --- networking -------------------------------------------------------
    # External, so the VM gets DHCP from the LAN router, can reach a mirror for
    # dnf, and is reachable from WSL2 by IP with no port forwarding. The
    # trade-off accepted here is that the VM is visible on the LAN.
    SwitchName   = 'fm-lab-external'
    SwitchType   = 'External'

    # Which physical adapter the external switch binds to. $null means "work it
    # out and refuse if the answer is ambiguous" -- New-TestLab.ps1 will list
    # the candidates rather than guess, because binding the wrong adapter drops
    # the host's own network for several seconds.
    HostAdapterName = $null

    # --- guest access -----------------------------------------------------
    # Created by the kickstart, used by Ansible. Not root: the lab should not
    # normalise logging in as root, and the service account work in C8 is
    # easier to reason about from an unprivileged starting point.
    AdminUser    = 'labadmin'

    # Public half is injected into the kickstart; private half stays in KeyDir
    # and never enters git. Generated by New-KickstartIso.ps1 if absent.
    SshKeyName   = 'fm-lab-ed25519'

    # --- guest configuration ---------------------------------------------
    # Kept here so that layer 1 can bake the same values the kickstart needs.
    # Everything ELSE about the guest is Ansible's job (layer 2).
    Hostname     = 'fm-rocky9-01'
    Timezone     = 'UTC'
}
